version: '3'

services:
  web:
    build:
      target: prod
    environment:
      - DJANGO_DEBUG=False

  celery:
    build:
      target: prod
    entrypoint: celery -A python_task worker --loglevel=info
