# Generated by Django 4.2.9 on 2024-02-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_collector_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="collector",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
